SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO u VALUES('Curso Basico', 'System', 'Administrator', 'admin@lasaedu.t-ecogroup.net', 'Profesor');
INSERT INTO u VALUES('Curso Basico', 'noemi', 'lee', 'nmolinaabreu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'System', 'Administrator', 'admin@lasaedu.t-ecogroup.net', 'Profesor');
INSERT INTO u VALUES('Electrónica Bàsica', 'Porfirio', 'Antonio Hernandez Lopez', 'porfipelis@gmail.com', 'Profesor');
INSERT INTO u VALUES('Electrónica Bàsica', 'Victor Manuel', 'Basilio', 'Victorlasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Anabel', 'Cabrera', 'anabelcabrera407@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Lino', 'Cesar Santos', 'Linolasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Roberto', 'David Rivera', 'Robertolasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Gabriel', 'de Jesus Diaz', 'Gabriellasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Enmanuel', 'de Jesus Ferreiras', 'Enmanuellasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Diego', 'de Jesus Pichardo', 'Diegolasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Wilbert Alexander', 'De la Cruz', 'Wilbertlasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Jefferson', 'Elian Guzman', 'Jeffersonlasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Manuel Adolfo', 'Guzman', 'Manuellasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Georgina', 'Herrera', 'ginah15@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Arisleidy', 'Jorge', 'Arisleidylasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Frammy', 'Jose Perez', 'perezframmyjose@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'noemi', 'lee', 'nmolinaabreu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Nelson', 'Luis Núñez', 'Nelsonlasaedu@gmial.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Pedro', 'Manauel Ovalles', 'pedromanuelovalles2004@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Cristian', 'Manuel Burgos', 'cristianburgos069515@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Lucas Damiel', 'Marizan  Pichardo', 'lucasdanielmarizan@gmail.com', 'Profesor');
INSERT INTO u VALUES('Electrónica Bàsica', 'Jonas', 'Mencia', 'menciajonas09@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Jose', 'Miguel Lopez', 'JoseMiguellasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Osiris', 'Munoz', 'osiris@osiris.com', 'Otro Rol');
INSERT INTO u VALUES('Electrónica Bàsica', 'Juan', 'Pablo Paulino', 'Juanlasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Anderson', 'Perez', 'Andersonlasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Braulio', 'Radhames Sanchez', 'braulio.sanchez0120@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Frankely', 'Rafael Sanchez', 'Frankelylasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Manuel', 'Ramon Cruz', 'sandycruz052326@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Jose', 'Ramon Peralta', 'Joselasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Josue', 'Ramos', 'ramosjosue060705@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Arismendy', 'Ramos', 'Arismendylasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Domingo Alexander', 'Rodriguez', 'Domingolasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Manuel', 'Sanchez', 'Manuel.Sanchez@laaurora.do', 'Otro Rol');
INSERT INTO u VALUES('Electrónica Bàsica', 'Alexander', 'Severino', 'Alexanderlasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Martin', 'Vargas', 'Martin.Vargas@LaAurora.do', 'Otro Rol');
INSERT INTO u VALUES('Electrónica Bàsica', 'Hansel Miguel', 'Vasquez', 'Elpapitoproblema@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Bàsica', 'Kirsy', 'Ventura', 'Kirsyventuraventura@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'System', 'Administrator', 'admin@lasaedu.t-ecogroup.net', 'Profesor');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Porfirio', 'Antonio Hernandez Lopez', 'porfipelis@gmail.com', 'Profesor');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Dariel Alexandro', 'Beato arias', 'darielarias04@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Luis de Jesús Mateo', 'de Jesús Mateo', 'amaurimateo29@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Wilbert Alexander', 'De la cruz Rodriguez', 'Delacruzwilbert65@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Brailin Ricardo', 'Domínguez Henríquez', 'brailindominguez8@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Miosotis Miguelina', 'González Ferrera', 'miosotis1131@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Manuel Adolfo', 'Guzman', 'Manuellasaedu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Jonathan guarionez', 'Inoa  Valdez', 'jonathanynoa0605@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Vanessa', 'Lopez angeles', 'Vl77624@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Yaniris', 'Martinez', 'yanirism264@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Johan', 'martinez', 'el.johan.18.m@icloud.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Chewin Ricardo', 'Mosquea Taveras', 'Chewintaveraz5@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Fernando Andrés', 'Pichardo León', 'fernandopichardoleon@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Victor Nehemías', 'Polanco castillo', 'polancov524@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Jennifer', 'ramos placencia', 'jenniferramos2122@icloud.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Rubelia antonia', 'Ramos Rodríguez', 'rubeliasexy1993.as@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Luis Alfonso', 'Ramos Rosso', 'lr3313360@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Luis Ángel', 'Rodriguez Guzmán', 'azca1325@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Yadelkis Altagracia', 'Rodríguez Montesino', 'yadelkisrodriguez27@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Darling David', 'salcedo arroyo', 'darlingsalcedo@icloud.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Jhostin', 'Valdez Almonte', 'Jhostinvaldez25@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Martin', 'Vargas', 'Martin.Vargas@LaAurora.do', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Hansel Miguel', 'Vasquez', 'Elpapitoproblema@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Charli de Jesús', 'veras rodriguez', 'Charliveras@hotmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segunda Generación  ', 'Wilquin', 'Yoan lajara', 'Wilquinyoanlajara@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'System', 'Administrator', 'admin@lasaedu.t-ecogroup.net', 'Profesor');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Porfirio', 'Antonio Hernandez Lopez', 'porfipelis@gmail.com', 'Profesor');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Leonardo', 'Antonio Veras', 'Leonardolasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Jennifer', 'Basilio', 'Jenniferlasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Juan Carlos', 'Burgos', 'Juanlasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Carla', 'Elizabeth Espinal', 'Carlaespinallasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Johan', 'Fernando Martinez', 'Johanmarinezlasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Arinson', 'Jose Santos', 'Arinsonlasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'noemi', 'lee', 'nmolinaabreu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Lucas Damiel', 'Marizan  Pichardo', 'lucasdanielmarizan@gmail.com', 'Profesor');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Jose Antonio', 'Mejia', 'Josemejialasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'joel', 'pena', 'joelosiris11@gmail.com', 'Otro Rol');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Digna Yaneri', 'Polanco', 'Dignalasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Victor Nehemias', 'Polanco', 'Victorpolancolasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Jose Gregorio', 'Rodriguez', 'Joselasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Manuel', 'Sanchez', 'Manuel.Sanchez@laaurora.do', 'Otro Rol');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Luis Miguel', 'Sosa', 'miguelgs260@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Ronald', 'Taveras', 'Ronallasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Martin', 'Vargas', 'Martin.Vargas@LaAurora.do', 'Profesor');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Martin', 'Vargas', 'Martin.Vargas@LaAurora.do', 'Otro Rol');
INSERT INTO u VALUES('Electrónica Básica - Segundo Grupo', 'Rosmerlyn', 'Williana Nuñez', 'Rosmerlynlasa@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Maquina PMB', 'System', 'Administrator', 'admin@lasaedu.t-ecogroup.net', 'Profesor');
INSERT INTO u VALUES('Maquina PMB', 'noemi', 'lee', 'nmolinaabreu@gmail.com', 'Estudiante');
INSERT INTO u VALUES('Programa Integral de Calidad para la Industria de Manufactura de Cigarros', 'System', 'Administrator', 'admin@lasaedu.t-ecogroup.net', 'Profesor');
INSERT INTO u VALUES('Programa Integral de Calidad para la Industria de Manufactura de Cigarros', 'Demo', 'Calidad', 'lauralorenzo1014@gmail.com', 'Otro Rol');
INSERT INTO u VALUES('Programa Integral de Calidad para la Industria de Manufactura de Cigarros', 'Damaris', 'Diaz', 'Damaris.Diaz@laaurora.do', 'Otro Rol');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
